#!/bin/bash
readme=$(cat esoui-readme.txt)
changelog=$(cat esoui-changelog.txt)
curl -H "x-api-token: $1"  -F "id=$2" -F "updatefile=@$3" -F "version=$4" -F "compatible=$5" -F "description=$readme" -F "changelog=$changelog" https://api.esoui.com/addons/update